version: 2.1

workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy

jobs:
  deploy:
    docker:
      - image: kalilinux/kali-rolling
    steps:
      - checkout
      - run:
          name: smth
          command: |
            apt update -q --fix-missing && apt upgrade -y
            apt -y install --no-install-recommends sudo wget curl dbus-x11 xinit openssh-server kali-desktop-xfce ca-certificates unzip git
            sudo apt -y install locales
            sudo sed -i s/^#\ en_US.UTF-8\ UTF-8/en_US.UTF-8\ UTF-8/ /etc/locale.gen
            sudo locale-gen
            echo "#!/bin/bash" > /startkali.sh
            echo "/etc/init.d/ssh start" >> /startkali.sh
            sudo chmod 777 /startkali.sh
            sudo apt -y install --no-install-recommends kali-linux-core
            sudo useradd -m -s /bin/bash -G sudo kali
            echo "kali:kali" | sudo chpasswd
            sudo rm /etc/xdg/autostart/xfce4-power-manager.desktop >/dev/null 2>&1
            sudo apt -y install --no-install-recommends tigervnc-standalone-server tigervnc-tools
            sudo echo "/usr/libexec/tigervncsession-start :8" >> /startkali.sh
            sudo echo "echo -e 'kali' | vncpasswd -f > /home/kali/.vnc/passwd" >> /startkali.sh
            sudo echo "while true; do sudo -u kali vncserver -fg -v; done" >> /startkali.sh
            sudo echo ":8=kali" | sudo tee -a /etc/tigervnc/vncserver.users
            sudo echo '$localhost = "no";' | sudo tee -a /etc/tigervnc/vncserver-config-mandatory
            sudo echo '$SecurityTypes = "VncAuth";' | sudo tee -a /etc/tigervnc/vncserver-config-mandatory
            sudo mkdir -p /home/kali/.vnc
            sudo chown kali:kali /home/kali/.vnc
            touch /home/kali/.vnc/passwd
            sudo chown kali:kali /home/kali/.vnc/passwd
            chmod 600 /home/kali/.vnc/passwd
            sudo echo "/bin/bash" >> /startkali.sh
            sudo /startkali.sh &
            wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x cloudflared
            chmod +x cloudflared
            wget https://github.com/novnc/noVNC/archive/refs/tags/v1.5.0.zip
            unzip v1.5.0.zip 
            ./noVNC-1.5.0/utils/novnc_proxy & ./cloudflared --url https://localhost:6080 --no-tls-verify & ./cloudflared --url tcp://localhost:5908 --no-tls-verify && sleep 60
