name: Cloudflare Tunnel Deployment

on:
  push:
    branches:
      - main  # Adjust based on your branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: linuxserver/webtop:ubuntu-mate
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Racket and Dependencies
      run: |
        sudo apt update
        sudo apt-get install racket -y

    - name: Download Cloudflared
      run: |
        curl -L -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod +x cloudflared

    - name: Run Cloudflare Tunnel
      run: |
        ./cloudflared --url http://localhost:3000 --no-tls-verify

    - name: Environment Setup
      run: echo "Cloudflare Tunnel successfully started"
      # Additional environment-related tasks can be placed here
