name: Cloudflare Tunnel Deployment

on:
  push:
    branches:
      - main  # Adjust based on your branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: kalilinux/kali-rolling  # You can choose other available runners like windows-latest or macos-latest
    steps:
    - name: Install vnc stuff
    - run: apt update -q --fix-missing && apt upgrade -y 
    - run: apt -y install --no-install-recommends sudo wget curl dbus-x11 xinit openssh-server kali-desktop-${DESKTOP_ENVIRONMENT}
    - run: apt -y install locales
    - run: sed -i s/^#\ en_US.UTF-8\ UTF-8/en_US.UTF-8\ UTF-8/ /etc/locale.gen
    - run: locale-gen
    - run: echo "#!/bin/bash" > /startkali.sh
    - run: echo "/etc/init.d/ssh start" >> /startkali.sh
    - run: chmod 755 /startkali.sh
    - run: apt -y install --no-install-recommends kali-linux-core
    - run: useradd -m -s /bin/bash -G sudo kali
    - run: echo "kali:kali | chpasswd"
    - run: echo "Port 20022" >>/etc/ssh/sshd_config
    - run: rm /etc/xdg/autostart/xfce4-power-manager.desktop >/dev/null 2>&1
    - run: if [ -e /etc/xdg/xfce4/panel/default.xml ] ; then sed -i s/power/fail/ /etc/xdg/xfce4/panel/default.xml ; fi
    - run: | 
        apt -y install --no-install-recommends tigervnc-standalone-server tigervnc-tools; \
        echo "/usr/libexec/tigervncsession-start :8 " >> /startkali.sh ; \
        echo "echo -e 'kali' | vncpasswd -f >/home/kali/.vnc/passwd" >> /startkali.sh  ;\
        echo "while true; do sudo -u kali vncserver -fg -v ; done" >> /startkali.sh ; \
        echo ":8=kali" >>/etc/tigervnc/vncserver.users ;\
        echo '$localhost = "no";' >>/etc/tigervnc/vncserver-config-mandatory ;\
        echo '$SecurityTypes = "VncAuth";' >>/etc/tigervnc/vncserver-config-mandatory ;\
        mkdir -p /home/kali/.vnc ;\
        chown kali:kali /home/kali/.vnc ;\
        touch /home/kali/.vnc/passwd ;\
        chown kali:kali /home/kali/.vnc/passwd ;\
        chmod 600 /home/kali/.vnc/passwd ;\
    - run: echo "/bin/bash" >> /startkali.sh
    - run: /startkali.sh &


    - name: Download Cloudflared
      run: |
        curl -L -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        chmod +x cloudflared

    - name: Run Cloudflare Tunnel
      run: ./cloudflared --url http://localhost:3000 --no-tls-verify

